import type { Metadata } from "next";
import { Comfortaa, Cinzel } from "next/font/google";
import "../styles/globals.scss";

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} ${cinzel.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
